from .base import *
from .env import DATABASES, SECRET_KEY, ACCESS_KEY, SECRET_ACCESS_KEY, ALGORITHM
DEBUG = False

SECRET_KEY = SECRET_KEY
DATABASES = DATABASES

ALGORITHM = ALGORITHM

ACCESS_KEY = ACCESS_KEY
SECRET_ACCESS_KEY = SECRET_ACCESS_KEY
